### ISSUE TITLE
Command-line interface does not find model files recursively.

### ISSUE THREAD

**Issue by bandurvp** [overturetool/vdm2c#9] opened 2016-06-21 08:39 UTC
Seems to be related to a faulty implementation of the required recursion, have asked PJ to take a look.

**Comment by peterwvj** [comment] 2016-06-21 08:47
Can't remember you asked me :) It must have been a long time ago. Can you please remind me?

**Comment by bandurvp** [comment] 2016-06-21 08:49
Hi Peter,

I wrote you a Skype message about this yesterday, see if you can find it, I explain it there.

Victor

**Comment by peterwvj** [comment] 2016-06-21 08:52
I missed it, sorry. I probably signed off before I received it.

**Comment by peterwvj** [comment] 2016-06-21 09:04
On mine it works well. Consider the file structure created below.

```
peter@peter-pc:~/Desktop$ mkdir tmp
peter@peter-pc:~/Desktop$ cd tmp/
peter@peter-pc:~/Desktop/tmp$ touch test1.txt
peter@peter-pc:~/Desktop/tmp$ touch test2.txt
peter@peter-pc:~/Desktop/tmp$ mkdir tmp1
peter@peter-pc:~/Desktop/tmp$ cd tmp1/
peter@peter-pc:~/Desktop/tmp/tmp1$ touch test3.txt
peter@peter-pc:~/Desktop/tmp/tmp1$ 
```

When I run the small program below...

```
public static void main(String[] args)
{
  File file = new File("/home/peter/Desktop/tmp");
  List<File> files = getFilesRecursively(file);
  for(File f : files)
  {
    System.out.println(f.getAbsolutePath());
  }
}
```

...It finds all tree files.

```
/home/peter/Desktop/tmp/test2.txt
/home/peter/Desktop/tmp/tmp1/test3.txt
/home/peter/Desktop/tmp/test1.txt
```

Did you expect a different behavior? How do you invoke it?

**Comment by bandurvp** [comment] 2016-06-21 09:12
I was invoking it on the command line from the main method in CGenMain in vdm2c and I was getting null pointer exceptions exactly as if I was passing in a phony model folder.  I was calling it on a model folder which only contains MATH.vdmrt in the subfolder lib and nothing else.

**Comment by peterwvj** [comment] 2016-06-21 09:25
Can you show me how to produce this problem? Also, can you confirm that `file.exists()` on your machine indeed does return true?

**Comment by bandurvp** [comment] 2016-06-21 09:26
Are you able to build overturetool/vdm2c?

**Comment by peterwvj** [comment] 2016-06-21 09:27
I can try to check it out. What branch?

**Comment by bandurvp** [comment] 2016-06-21 09:30
Development.  If you do mvn install it will create a JAR that has ``-with-dependencies'' in the name.  I ran that JAR on the model directory structure I told you about and got that result.  Originally, the implementation wasn't using the recursive function, so I changed it, without any success.

**Comment by peterwvj** [comment] 2016-06-21 09:32
I can build development without any problems. I'm not sure where the jar is or how to invoke it. Will you be in tomorrow?

**Comment by bandurvp** [comment] 2016-06-21 09:33
OK that's good.  I'm putting this problem on the backburner for a bit, because it's not blocking me, and it's not for AU, it's for someone at ESA doing something with the code generator, but it's not urgent.  I'm ill, but I'm getting better, so I should be in tomorrow.

**Comment by peterwvj** [comment] 2016-06-21 09:38
Sorry about that. Hope you get well soon. Regarding the issue - that's fine. I'm happy to help sort it out when you plan to look into it.

**Comment by bandurvp** [comment] 2016-06-21 09:41
Thanks!  The recursive thing is not an immediate impediment to the guy at ESA, but I wanted to get it to work properly, because I want the code generator to have the same capability on the command line as it does from within Overture.  I'll come around tomorrow.

**Comment by peterwvj** [comment] 2016-09-20 10:13
This issue seems to be fixed. As explained above, I've confirmed that `getFilesRecursively` works. The example below demonstrates that the command-line (CLI) tool finds model files recursively.

``` bash
peter@peter-pc:~/Desktop/tmp/rec-files$ find . -type f
./A.vdmrt
./other/B.vdmrt
```

Invoke the CLI and pass it the source and destination folders:

```
-sf /home/peter/Desktop/tmp/rec-files
-dest /home/peter/Desktop/tmp/rec-files/out
```

The output folder contains both classes:

``` bash
peter@peter-pc:~/Desktop/tmp/rec-files$ ls out/
A.c
A.h
B.c
B.h
```

I'll close this issue for now. If I'm missing something or you find a way to produce this problem please re-open the issue.

**Closed as completed by peterwvj** 2016-09-20 10:13 UTC
